### ISSUE TITLE
Testing endpoint

### ISSUE THREAD

**Issue by sebdomdev** [recurly/recurly-client-android#12]
There doesn't seem to be a way to use a url that points to a testing endpoint for development and QA purposes. In RecurlyConfig.java, the url "https://api.recurly.com" is hard coded and cannot be changed. So you can only use recurly in production and there is no way of testing it.

**Comment by drewish** [comment]
All the traffic goes to the same domain but the public key determines which site is used. So feel free to sign up for a sandbox site and do your testing with that site's public key.
